# Generated by Django 3.2.6 on 2021-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('what_youll_learn', models.TextField()),
                ('pre_requisites', models.TextField()),
                ('content', models.TextField()),
                ('question', models.TextField()),
                ('solution', models.TextField()),
                ('has_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
