# Generated by Django 3.2.6 on 2021-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='input',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='output',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
